security:
  encoders:
    FOS\UserBundle\Model\UserInterface: sha512

  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      form_login:
        provider: fos_userbundle
        login_path: /login
        check_path: /login_check
        success_handler: redirect.after.login
      logout:
        path: /logout
        target: /
      anonymous:    true


  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/membre, role: ROLE_USER }
    - { path: ^/crm, role: ROLE_COMMERCIAL }
    - { path: ^/admin, role: ROLE_ADMIN }