<?php

namespace ES\AdminBundle\Repository;

/**
 * ReglageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglageRepository extends \Doctrine\ORM\EntityRepository
{
}
