vich_uploader:
    db_driver: orm
    mappings:
        site_logo:
            uri_prefix:         '%app.path.site_logo%'
            upload_destination: '%kernel.root_dir%/../web/%app.path.site_logo%'
        article_image:
            uri_prefix:         '%app.path.article_images%'
            upload_destination: '%kernel.root_dir%/../web/%app.path.article_images%'